### PR TITLE
Fixed 3 typos

### PR DESCRIPTION
**Pull request by Piotr1215**
Hi, apologies if those were already found, but I've spotted those 3 typos. 

I'm not sure if the patch is the right way to contribute, if not please LMK.

### CODE REVIEW

**Review by lloydchang — APPROVED** [review]
@Piotr1215 You may want to add suggestions in https://github.com/open-gitops/documents/pull/22

Simultaneously spanning _before and after_ you submitted here, all 3 typos:
1. acheived -> achieved
2. occured -> occurred
3. configiuration -> configuration
are _now also_ suggested for correction in https://github.com/open-gitops/documents/pull/22

Since I agree with all 3 typo fixes presented here, I approved this pull request.  Practically-speaking, your proposed changes may end up being folded into https://github.com/open-gitops/documents/pull/22 which now have the same 3 typo fixes in aggregate.  This depends on how @scottrigby wants to process both pull requests https://github.com/open-gitops/documents/pull/22 and https://github.com/open-gitops/documents/pull/23.

Thank you @Piotr1215 and @scottrigby

**Review by todaywasawesome — APPROVED** [review]

**Comment by lloydchang** [comment]
🚀  Thank you @Piotr1215 @todaywasawesome @scottrigby

**Comment by Piotr1215** [comment]
> @Piotr1215 You may want to add suggestions in #22
> Since I agree with all 3 typo fixes presented here, I approved this pull request. Practically-speaking, your proposed changes may end up being folded into #22 which now have the same 3 typo fixes in aggregate. This depends on how @scottrigby wants to process both pull requests #22 and #23.
>

Thank you for explaining @lloydchang. The reason I did a patch was that I had no access to comment on code for #22 , but I could always mention in what file the typos were.

**Comment by lloydchang** [comment]
@Piotr1215 I believe the access issue is because of:
> We went looking everywhere, but couldn’t find those commits.  **Sometimes commits can disappear after a force-push.** Head back to the latest changes here.

Here's a screenshot of what I see when that happens:
We went looking everywhere, but couldn’t find those commits  Sometimes commits can disappear after a force-push  Head back to the latest changes here

**Comment by lloydchang** [comment]
Related, https://github.com/open-gitops/documents/pull/22#discussion_r718074004
> I think we should add Co-authored-by trailers to the commit from #23, since it was recommended here as well. We can still rewrite commits in this PR branch before anything gets committed to main.

@scottrigby, if you want to add the 3 co-authors, they are:
1. @squaremo for "achieved"
2. @ckavili for "configuration"
3. @lloydchang for "occurred"

**Pull request merged**
