### PR TITLE
German translations of principles and glossary

### PR DESCRIPTION
**Pull request by heubeck**
Addresses https://github.com/open-gitops/documents/issues/53
Solves https://github.com/open-gitops/documents/issues/52

Contributors:
@mrempel23
@stuebingerb
@steinbrueckri
@beiertu-mms
@buerkle-mms
@aldimann
@kharf
@heubeck

Yours sincerely
[Java User Group Ingolstadt](https://jug-in.bayern) and Friends

### CODE REVIEW

**Comment by heubeck** [comment]
@scottrigby
@schlomo 
@LutzLange

**Comment by schlomo** [comment]
Beautiful and spot on translation, I am very much impressed (having tried myself).

Maybe we shouldn't use country icons to represent languages? There are also German speakers who don't live in Germany...

**Comment by heubeck** [comment]
> Beautiful and spot on translation, I am very much impressed (having tried myself).
> 
> Maybe we shouldn't use country icons to represent languages? There are also German speakers who don't live in Germany...

Thank you, and good catch: I've removed to flag.

**Comment by christianh814** [comment]
Total der Hammer!

Going to go through this later today, but my German is only at a B1/B2 level so I'll need some help from @schlomo

**Review by christianh814 — APPROVED** [review]
This all looks good to me. We should have another person look through it though before merging

**Review by Vad1mo — APPROVED** [review]

**Review by sluetze — APPROVED** [review]
Not sure if you would have to define "IST-Zustand" if you already define "SOLL-Zustand", but it should be common knowledge.

**Comment by stuebingerb** [comment]
> Not sure if you would have to define "IST-Zustand" if you already define "SOLL-Zustand", but it should be common knowledge.

We were unsure how far we should deviate from the original source. There were a few details we struggled with in English and the English glossary e.g. also only explains the "desired state".

In the end we decided to start with a translation as close as possible to the source but we'd surely be open for a more general discussion as well.

**Comment by sluetze** [comment]
> We were unsure how far we should deviate from the original source. There were a few details we struggled with in English and the English glossary e.g. also only explains the "desired state".

yes. I just remembered, that this is a translation. Nevermind. my fault.

**Comment by christianh814** [comment]
Okay to merge? @scottrigby

**Comment by scottrigby** [comment]
Nice work everyone! 🇩🇪😀

@christianh814 we could create a 1.1.0 release that includes this translation. Corrections to translations could be in patch versions.

@heubeck only suggestion is adding Co-authored-by commit trailer lines for each person you already credited in the commit message! Do you have their names and GitHub emails/anonymous emails? We have done this with PRs representing precious group efforts: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by heubeck** [comment]
Thank you @scottrigby, we did the co-authored now properly.

**Comment by schlomo** [comment]
FYI, there are also technical reasons for not using flag emojis to denote language, as apparently Windows doesn't support that, see https://youtu.be/_mZBa3sqTrI?t=2915

I cannot validate this since I lack a suitable test environment, but I thought that it might help here to know about this.

**Comment by scottrigby** [comment]
Thank you, everyone! Really impressed by the collective effort here 👏 🎉💪

**Pull request merged**
