### PR TITLE
update spanish translation

### PR DESCRIPTION
**Pull request by varodrig**
This PR update the Spanish translation of the Principles and Glossary.

### CODE REVIEW

**Comment by varodrig** [comment]
As per discussion with the group all translations requires multiple reviewers. 
cc @todaywasawesome 
Eduardo offered to reviewed.

**Comment by varodrig** [comment]
I'm waiting for reviewers. please review and accept or add feedback. thank you

**Review by espotti — APPROVED** [review]
I saw all translations ok. Spanish expressions are ok based on project context.

**Comment by varodrig** [comment]
Thank you 

> I saw all translations ok. Spanish expressions are ok based on project context.

thank you so much @espotti

**Comment by varodrig** [comment]
@todaywasawesome can you approve?

**Review by todaywasawesome — APPROVED** [review]
I don't speak Spanish but it sounds like we have an approval from someone who does.

**Comment by varodrig** [comment]
thank you @todaywasawesome

**Pull request merged**
