### PR TITLE
Add Macedonian translation

### PR DESCRIPTION
**Pull request by gocemitevski**
This PR adds Macedonian translations of the Principles and Glossary. It also updates the README to include Macedonian in the listings.

### CODE REVIEW

**Comment by todaywasawesome** [comment]
@gocemitevski do you think you could ask another Macedonian speaker to review this? It would help!

**Comment by gocemitevski** [comment]
> @gocemitevski do you think you could ask another Macedonian speaker to review this? It would help!

Sure. @gdamjan interested?

**Comment by todaywasawesome** [comment]
@gdamjan are you still able to do a review?

**Comment by gdamjan** [comment]
yeah
I did a once over, let me click the review button tomorrow

**Comment by JaimeMagiera** [comment]
@gdamjan Were the latest rounds of changes acceptable? Just checking in on the status of the PR.

**Review by gdamjan — APPROVED** [review]

**Comment by gocemitevski** [comment]
@JaimeMagiera @todaywasawesome is this ready to go?

**Review by todaywasawesome — APPROVED** [review]

**Pull request merged**
